[2024-02-17 15:52:40,306: INFO: main: Welcome to Our custom logging]
[2024-02-23 17:37:15,552: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:37:15,557: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:37:15,559: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:37:15,560: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    config = ConfigurationManager()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
  File "/Users/pardhu/anaconda3/envs/textS/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 32, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-02-23 17:41:47,483: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:41:47,489: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:41:47,491: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:41:47,492: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    config = ConfigurationManager()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
  File "/Users/pardhu/anaconda3/envs/textS/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 32, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-02-23 17:44:56,026: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:44:56,032: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:44:56,036: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:44:56,036: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    config = ConfigurationManager()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
  File "/Users/pardhu/anaconda3/envs/textS/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 32, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-02-23 17:57:01,341: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:57:01,345: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:57:01,348: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:57:01,348: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    config = ConfigurationManager()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
  File "/Users/pardhu/anaconda3/envs/textS/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 32, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-02-23 17:58:11,334: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:58:11,338: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:58:11,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:58:11,342: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 31, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    config = ConfigurationManager()
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
  File "/Users/pardhu/anaconda3/envs/textS/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/pardhu/Documents/ML_Projects/NLP_Text_Summarizer/src/textSummarizer/utils/common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-02-23 17:59:36,162: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-23 17:59:36,167: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-23 17:59:36,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-23 17:59:36,171: INFO: common: created directory at: artifacts]
[2024-02-23 17:59:36,171: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-23 17:59:39,066: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 8274362
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6067cb05b4d8701b71f8c029f97cd00c5bc1144cb94632e0db74389cc0c2ab84"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B78A:74426:506064:64DEF8:65D92355
Accept-Ranges: bytes
Date: Fri, 23 Feb 2024 22:59:37 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4637-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1708729177.684776,VS0,VE331
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3c85ce91a96df287d7dd874de6eb6005126a18be
Expires: Fri, 23 Feb 2024 23:04:37 GMT
Source-Age: 0

]
[2024-02-23 17:59:39,328: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
